[project]
name = "ai-council"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "elevenlabs>=2.27.0",
    "fastapi[standard]>=0.128.0",
    "faster-whisper>=1.2.1",
    "keyboard>=0.13.5",
    "langchain>=1.2.0",
    "langchain-community>=0.4.1",
    "langchain-openai>=1.1.6",
    "librosa>=0.11.0",
    "numba>=0.63.1",
    "nvidia-cublas-cu12>=12.8.4.1",
    "pocket-tts>=1.0.2",
    "pyaudio>=0.2.14",
    "pydub>=0.25.1",
    "redis>=7.1.0",
    "sounddevice>=0.5.5",
    "streamlit>=1.52.2",
    "webrtcvad-wheels>=2.0.14",
]
